export const cards = [
  {
    text: "Enjoy the richness of pure, farm-fresh milk — crafted to bring out nature’s real taste in every sip.",
    name: "Geeta, Student",
    rotation: "-rotate-[10deg]",
    translation: "-translate-y-[5%]",
    color: "#E8AB09",
    bg: "#FFF6D2",
  },
  {
    text: "The creamy texture and freshness remind me of my childhood days in the village. Absolutely love it!",
    name: "Rohit, Fitness Trainer",
    rotation: "rotate-[4deg]",
    translation: "-translate-y-[10%]",
    color: "#9E28D9",
    bg: "#F9E8FF",
  },
  {
    text: "Finally found a brand that delivers both taste and purity. My morning coffee feels complete now.",
    name: "Neha, Software Engineer",
    rotation: "-rotate-[4deg]",
    translation: "translate-y-[10%]",
    color: "#009688",
    bg: "#D9FFF3",
  },
  {
    text: "It’s so refreshing and natural — no preservatives, no weird taste, just pure milk goodness.",
    name: "Amit, Photographer",
    rotation: "rotate-[4deg]",
    translation: "translate-y-[15%]",
    color: "#E91E63",
    bg: "#FFE4EE",
  },
  {
    text: "Smooth, tasty, and light — perfect for shakes and cereals. My family’s favorite choice! Delicious",
    name: "Kiran, Homemaker",
    rotation: "-rotate-[10deg]",
    translation: "-translate-y-[5%]",
    color: "#3F51B5",
    bg: "#E8EBFF",
  },
  {
    text: "This milk feels so authentic. You can literally taste the difference — rich and full-bodied. tasty!!",
    name: "Sonia, Nutritionist",
    rotation: "rotate-[4deg]",
    translation: "translate-y-[5%]",
    color: "#388E3C",
    bg: "#E4FEE4",
  },
];
